config/routes.rb
RailsFramework::Application.routes.draw do
  root :to => 'session#splash'
  resources :subscribers, :only=> [:index,:new,:create] do
    collection do
      post :purchase
    end
  end
  resources :users, :only => [:index, :new, :create]

  get '/login' => 'session#new'

  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  role       :string(255)
#  ssn        :string(255)
#  tel        :string(255)
#

class Administrator < ActiveRecord::Base
  attr_accessible :role, :ssn,:tel
  validates :role, :presence => true
  has_one :user, :as => :userable
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id              :integer          not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  gender          :string(255)
#  age             :integer
#  occupation      :string(255)
#  hobbies         :string(255)
#  tagline         :string(255)
#  bio             :string(255)
#  subscription_id :integer
#  expires         :date
#

class Subscriber < ActiveRecord::Base
  attr_accessible :gender, :age,:occupation,:hobbies,:tagline,:bio,:expires
  has_one :user, :as => :userable
  belongs_to :subscription
  validates :tagline, :presence => true
  validates :gender, :presence => true
  validates :age, :numericality =>  { :only_integer => true}

  def has_subscription?
    self.subscription.present?
  end

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id         :integer          not null, primary key
#  plan       :string(255)
#  duration   :integer
#  cost       :decimal(, )
#  num_photos :integer
#  num_emails :integer
#  num_texts  :integer
#  is_alist   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class  Subscription < ActiveRecord::Base
  attr_accessible :plan,:duration,:cost,:num_photos,:num_emails,:num_texts,:is_alist
  has_many :subscribers
  #before_save :default_values

=begin
  private
  def default_values
    self.is_alist ||= false
  end
=end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  userable_id     :integer
#  userable_type   :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation
  belongs_to :userable,  :polymorphic => true
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :username, :presence => true
  has_secure_password

  def sub
    self.userable.is_a?(Subscriber) ? self.userable : false
  end

  def admin
    self.userable.is_a?(Administrator) ? self.userable : false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

before_filter :authenticate
private
def authenticate
  @auth = User.find(session[:user_id]) if session[:user_id].present?
end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def splash
    @subscriber = Subscriber.new
  end

  def new
  end

  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      @auth = User.find(session[:user_id]) if session[:user_id].present?
    else
      session[:user_id] = nil
    end
  end

  def destroy
    session[:user_id] = nil
    @auth = nil
  end


end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @user = User.new
  end

  def create
        @user = User.new(params[:user])
        if @user.save
            s1 = Subscriber.create(tagline:"Change me",gender:"Select",age:10)
            s1.user = @user
        end
  end

  def purchase
      plan = Subscription.where(plan:params[:plan]).first();
      @auth.sub.subscription = plan
      @auth.sub.expires = Time.now + (!plan.duration.nil? ? plan.duration : 0)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def is_auth
      @auth.present?
    end
    def subscription_levels
      Subscription.all
    end

end

app/views/layouts/_adminbar.html.haml
This is an admin bar.  Administrative tasks etc/links can be added here.

app/views/layouts/_header.html.haml
//HEADER (layouts/_header.html.haml)
/ =link_to("Login",login_path)
/ =link_to("Create Account",new_user_path)
/ = button_to("Logout", login_path, :method => :delete)


%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        %a{:href => "/"} Yakker
  %section.top-bar-section
    / Left Nav Section
    %ul.left
      %li.divider
      %li.active
        %a{:href => "#"} Main Item 1
      %li.divider
      %li
        %a{:href => "#"} Main Item 2
      %li.divider
      %li.has-dropdown
        %a{:href => "#"} Main Item 3
        %ul.dropdown
          %li.has-dropdown
            %a{:href => "#"} Dropdown Level 1a
            %ul.dropdown
              %li
                %label Dropdown Level 2 Label
              %li
                %a{:href => "#"} Dropdown Level 2a
              %li
                %a{:href => "#"} Dropdown Level 2b
              %li.has-dropdown
                %a{:href => "#"} Dropdown Level 2c
                %ul.dropdown
                  %li
                    %label Dropdown Level 3 Label
                  %li
                    %a{:href => "#"} Dropdown Level 3a
                  %li
                    %a{:href => "#"} Dropdown Level 3b
                  %li.divider
                  %li
                    %a{:href => "#"} Dropdown Level 3c
              %li
                %a{:href => "#"} Dropdown Level 2d
              %li
                %a{:href => "#"} Dropdown Level 2e
              %li
                %a{:href => "#"} Dropdown Level 2f
          %li
            %a{:href => "#"} Dropdown Level 1b
          %li
            %a{:href => "#"} Dropdown Level 1c
          %li.divider
          %li
            %a{:href => "#"} Dropdown Level 1d
          %li
            %a{:href => "#"} Dropdown Level 1e
          %li
            %a{:href => "#"} Dropdown Level 1f
          %li.divider
          %li
            %a{:href => "#"} See all →
      %li.divider
    / Right Nav Section
    %ul.right
      %li.divider
      %li
        =@auth.nil? ? link_to('Register', new_subscriber_path, :remote => true ) : link_to(@auth.username,"/login",:method=>"DELETE", :remote => true)
      %li.divider
      %li
        =@auth.nil? ? link_to('Login', "/login", :remote => true ) : link_to("Settings","#")
      -if !@auth.nil? && @auth.sub.present? && !@auth.sub.subscription_id.nil?
        %li.divider
        %li
          =link_to("Profile","#")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yakker</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='header'>
   <%= render :partial => 'layouts/header'%>
</div>
<div class='row'>
<br/>
  <%= yield %>
</div>


    <%= render :partial => 'layouts/footer'%>

    <!-- Including JS scripts on bottom to speed upload -->
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
</body>
</html>

app/views/layouts/xapplication.html.haml
!!!
%html
  %head
    %title RailsFramework
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  %body
    .row
      = render :partial => 'layouts/header'
    .row
      = is_auth ? "You are logged on" : "You are logged off"
      = is_admin ? render(:partial => 'layouts/adminbar') : ""
      %br/
      = yield
    .row
      = render :partial => 'layouts/footer'
    / Including JS scripts on bottom to speed upload
    = javascript_include_tag "application"

app/views/session/_form.html.haml
.row
  .large-5.columns
    = form_tag '/login', :remote => true do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Login', :class => 'button radius'
      = link_to('Cancel',"#", :'data-clear-form'=> true ,:class=>'button')
  .large-7.columns

app/views/session/create.js.erb
<% if session[:user_id].present? %>
    $('#login_form').empty();
    $('#header').empty().append("<%=j render(:partial => 'layouts/header')%>");
    $('#subscriptionbar').empty().append("<%=j render(:partial => 'subscriptions/subpurbar')%>");
<%else %>
    $('#login_form').empty().append("<%=j render(:partial => 'form')%>");
<%end%>

app/views/session/destroy.js.erb
alert("You have logged out!");
$('#header').empty().append("<%=j render(:partial => 'layouts/header')%>");
$('#subscriptionbar').empty().append("<%=j render(:partial => 'subscriptions/subpurbar')%>");

app/views/session/new.html.haml
.row
  .large-5.columns
    = form_tag '/login' do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Login', :class => 'button radius'
  .large-7.columns

app/views/session/new.js.erb
$('#subscriber_form').empty();
$('#login_form').empty().append('<%=j render(:partial => 'form') %>');

app/views/session/splash.html.haml
.form
  #subscriber_form
  #login_form


#subscriptionbar
  =render :partial => 'subscriptions/subpurbar'

app/views/shared/_errors.html.haml
- if object.errors.any?
  ="Please fix these #{pluralize(object.errors.count,'error')}"
  .errordiv
    - object.errors.full_messages.each do |msg|
      %br
      %span.radius.secondary.label=msg
      %br

app/views/subscribers/_form.html.haml
.row
  .large-5.columns
    =render(:partial => 'shared/errors', :locals => {:object=>@user})
    = form_for @user, :url => subscribers_path, :remote => true do |f|
      = f.label :username
      = f.text_field :username
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.submit(nil,:class => 'button')
      = link_to('Cancel',"#", :'data-clear-form'=> true ,:class=>'button')
  .large-7.columns

app/views/subscribers/create.js.erb
<% if @user.valid? %>
  $('#subscriber_form').empty();
  $('#subscriber_form').text('You have created an account');
  $('#subscriber_form').fadeOut(6000,function(){$('#subscriber_form').empty()})
<% else %>
  $('#subscriber_form').empty().append("<%=j render :partial =>'form' %>");
<%end%>

app/views/subscribers/new.js.erb
$('#login_form').empty();
$('#subscriber_form').empty().append('<%=j render(:partial => 'form') %>');

app/views/subscribers/purchase.js.erb
$('#subscriptionbar').remove();
alert("You just purchased: <%= @auth.sub.subscription.plan %>");

app/views/subscribers/showsubscriberform.js.erb
alert("Hello!");

app/views/subscriptions/_subpurbar.html.haml
-if (@auth.present? && !@auth.admin && !@auth.sub.subscription.present?)
  -subscription_levels.each do |subscription|
    =button_to(subscription.plan, purchase_subscribers_path(plan:subscription.plan) ,remote:true,:class=>'button radius inline')

app/views/users/new.html.haml
.row
  .large-5.columns
    = form_for @user do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.submit :class => 'button radus'
  .large-7.columns